name: Create Pull Request

on:
  push:
    branches:
      - fixes_general_1

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
         

      - name: create pull request
        run: gh pr create -B main -H junaid --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  

